### ISSUE TITLE
Compatibility with Speedway R120

### ISSUE THREAD

**Issue by jealcuna** [ransford/sllurp#130]
Hi everybody, I am thinking to buy the RFID reader Speedway R120. It does not look different to R220, so I suspect that this library should be compatible with the new reader.

Has anyone tested the reader yet?

Do you think is just a matter to configure some parameters to get work?

If it is not compatible, could you add this wonderful device to the list compatible in the future....?

Best regards,
J.C.

**Comment by ransford** [comment]
Hello! I haven't used the R120 yet, but I believe the only substantive difference between that and the R220/R420 is the number of antenna ports. The R120's [support page](https://support.impinj.com/hc/en-us/articles/202755358-Speedway-Revolution-Installation-Operations-Guide) implies that it supports LLRP just like its bigger siblings, so it should work fine with sllurp without any extra configuration.

Let us know if you *can't* get it to work! In the meantime I'll close this issue.
