### ISSUE TITLE
Code EDIT

### ISSUE THREAD

**Issue by Xzib** [ransford/sllurp#139]
I am trying to change the inventory.py file so that I can save the epc code in my database but it is not working.Everytime I run the /verb/inventory.py file on cmd "Python inventory.py" it does not do anything and returns to the console. please help

**Comment by ukrutt** [comment]
I think the preferred way to run inventory is via the `sllurp inventory <ip-address>` command.  Have you tried this?

Although I'd encourage you to not modify the `inventory` file but rather create a separate program that does what you want.  Your program could import `sllurp` and follow the pattern of `inventory.py` but leave `sllurp` itself unchanged.
