### ISSUE TITLE
how do i capture logging events of my reader

### ISSUE THREAD

**Issue by aymeri07** [ransford/sllurp#152]
Hi everybody,

i start my program for read tag ID, but after few minutes my program stop and i see in my log this message : 

> ```
> </READER_EVENT_NOTIFICATION>
> starting message callbacks for READER_EVENT_NOTIFICATION
> done with message callbacks for READER_EVENT_NOTIFICATION
> Got reader event notification
> lost connection: Connection was closed cleanly.
> ```

how do i capture exactly logging to my reader with sllurp ?

thank you so much.

soon.

**Comment by edmond1992** [comment]
Try this:
`import sllurp.log
import logging
logging.getLogger('sllurp').setLevel(logging.DEBUG)
sllurp.log.init_logging(debug=True, logfile='debug.txt')`

Either one set should do the job, but I like to read those log on screen directly and save to disk at the same time.
