### ISSUE TITLE
Mysql and raspberry pi

### ISSUE THREAD

**Issue by ineedhelpmysql** [ransford/sllurp#156]
Hello, i want to purchase one of the mentioned uhf rfid readers. I would like to ask. Can i use that library in raspberry-pi, in the python ide? And can i write those read datas in mysql database? thank you for your answers.

**Comment by ransford** [comment]
sllurp definitely works on Raspberry Pi.

There isn't a built-in MySQL interface, but you can build one yourself if you start from the small example in sllurp's README.

Have fun!
