### ISSUE TITLE
Changing data format of the sensor vales

### ISSUE THREAD

**Issue by goodwillM** [ransford/sllurp#158]
I am reading sensor data from AS321x-Eval-analog tag using R220 impinj reader
but the data that I am reading is in a format I do not understand, which is shown below as  "readData: b\xc0\x00".
how do I change this format to decimal and also how do I log the sensor values I am reading using windows command prompts?
I am using "sllurp access speedwayr-13-9F-37 -mb 3 -r 1 -wp 0 -X 30 -n 1" command to read the sensor data.

 'AntennaID': (1,),
  'EPCData': {'EPC': b'64211ff56baf60caccc31e225a14966149b26d6b859c0001',
              'EPCLengthBits': 192},
  'LastSeenTimestampUTC': (1611151260740983,),
  'OpSpecResult': {'OpSpecID': 0,
                   'ReadData': b'\xc0\x00',
                   'ReadDataWordCount': 1,
                   'Result': 0},

**Comment by ransford** [comment]
Good question! These fields can be pretty inscrutable. Unfortunately most
of the complexity comes from the standards that apply. sllurp is giving you
the raw bytes it read from the memory bank, hence the 'b' prefix. To make
your own callback for tag-memory reads (i.e., to do whatever you want with
those bytes), you can mimic the structure of
https://github.com/ransford/sllurp/blob/develop/sllurp/verb/access.py.

To figure out what the bytes mean, I recommend reading the part of your
tag's datasheet that covers its memory layout.
https://rfid4u.com/rfid-epc-gen2-memory/ is a good general introduction to
the standards. Bank 3 is the "user" memory, so the interpretation of its
contents are application and tag dependent.

Hope this helps. Good luck!
