### ISSUE TITLE
sllurp v2 error access

### ISSUE THREAD

**Issue by temp0508** [ransford/sllurp#159]
command   sllurp access -r 1 -wp 0 -mb 3 192.168.1.240

error

 File "sllurp\llrp_proto.py", line 1481, in encode_AccessSpec
    int(par['AntennaID']),

**Comment by ransford** [comment]
Hi, what version? `sllurp version` will tell you.

If you're on the latest (0.5.1 or `develop`), see if the `ransford/access-antennas` branch fixes your problem. This issue made me realize that `access` didn't take an antenna argument.
