### ISSUE TITLE
Problem reading more than 512 tags

### ISSUE THREAD

**Issue by sistemasc2** [ransford/sllurp#162]
Hi,
I've been working on some code for reading RFID tags using Zebra Readers (FX7500, FX9600). I need to save all the tags to a file, but previously I count the amount of tags to get sure of the amount of tags read.

Here, I set the self.tags value to the "tagReport.msgdict['RO_ACCESS_REPORT']['TagReportData']"

self.tags = tagReport.msgdict['RO_ACCESS_REPORT']['TagReportData']

But, if I use a len(self.tags)this is the result. 

root@srvrfid:/home/srvrfid/903pruebas# sh read.sh
Process running. Is alive? True
**512
512**
Closing Connection
Shutting down

I stop if after at least 2 reads of the same length. But that is a problem, because when it reaches that 512 limit, no more tags are read. This is a big issue, because we need to read more than 512. It doesn't matter if another 300 tags are ignored.

I've tried some examples I saw on internet, but it always limit the total amount of reads to 512. 
I checked my reader, and set the MaxNumberOfTagsBuffered to 1024:

<RadioProfileData><RadioRegisterData Address='0' Data='00'/>
</RadioProfileData>
<CustomProfileData ForceEAPMode='0' FIPS_MODE_ENABLED='0' MaxNumberOfTagsBuffered='**1024**'/>
</Motorola >

But it still only reads 512.

Did anybody experienced this before? Is there any solution? Is here someone that reads more than 512 tags on a single read?

**Comment by ransford** [comment]
There's no limit in sllurp, but it's possible you're running into a Gen2 protocol limitation or a limitation with your reader. For the latter question, perhaps you could look in the reader's manual to see if there's anything related to a read limit?

As for whether you're hitting a Gen2 protocol limitation, it's hard to tell. You could turn on debug-level logging per the README, or you might take a look at the `docs/` subdirectory of this repository.

**Comment by sistemasc2** [comment]
Hi,
Thanks for your reply.

I really do't know if I'm using Gen2 or which protocol. How can I check that? In the reader's manual there isn't any clue about this. I tried using the web based UI and it can read thousands of tags, but using sllurp it always stops at 512.

**Comment by ganeshasri** [comment]
We are also facing same type of issue.
Using sllurp we can read upto 200 tags easily but when we try reading 250 sllurp is reading only 240 tags.
But FX9600 web UI is reading all the tags.

**Comment by ransford** [comment]
I recommend using the `DEBUG` log level (you can see how `sllurp/verb/inventory.py` does this). If you discover ways the sllurp code can be improved, please submit a pull request.

sllurp is written in pure Python, so I'm generally not surprised when a compiled application (such as from a manufacturer) achieves higher overall throughput in a dense environment.

**Comment by fviard** [comment]
@ganeshasri You should try the fviard-develop-v2 branch:
https://github.com/ransford/sllurp/tree/fviard-develop-v2
