### ISSUE TITLE
I could not make "Quick Start" works

### ISSUE THREAD

**Issue by HawKoder** [ransford/sllurp#165]
I am newbie in Python, so, probably I am doing something wrong, but let me describe the problem:

I just copy and paste the Quick Start code to my python script, after I run it, I receive the following console log:

=============================================================== RESTART: C:\Program Files (x86)\Python\teste.py ==============================================================
tags: [{'EPC-96': b'300ed89f3350192000000362'}]

And then nothing more. I have a tag near my antenna and I am sure my reader is detecting the tag, but the code appears to be stucked in some part of the "reactor.read()" function.

Can you help me to understand what is happening?

**Comment by ransford** [comment]
I'd recommend experimenting with the `inventory` script as described in this repo's quick start instructions. That will help you figure out whether your reader is behaving properly.
