### ISSUE TITLE
Adding support for TDS 1.12

### ISSUE THREAD

**Issue by tushar-dadlani** [ransford/sllurp#166]
Hi, 

I noticed that the epc code works with TDS 1.9. A lot of products use TDS 1.12. Any plans to support TDS 1.12?

https://www.gs1.org/sites/default/files/docs/epc/GS1_EPC_TDS_i1_12.pdf

**Comment by ransford** [comment]
Hello! The code in `epc/` came from a contributor (@sheeley). I marked this as "good first issue" in case you or anyone else who sees this would like to contribute a pull request for TDS 1.12 support.
