### ISSUE TITLE
How to get Reader Antenna status

### ISSUE THREAD

**Issue by ganeshasri** [ransford/sllurp#170]
Please let us know how to get Reader Antenna status using sllurp code?

Can we get Antenna status using llrp?

**Comment by ransford** [comment]
There's limited support for AntennaEvent messages. If you search for `READER_EVENT_NOTIFICATION`, you'll see where you might be able to add code to handle AntennaEvent messages for connection or disconnection of antennas.

**Comment by ganeshasri** [comment]
We used SNMP method to get RFID reader antenna status and it is working fine.
