### ISSUE TITLE
Support manufacturer extensions

### ISSUE THREAD

**Issue by ransford** [ransford/sllurp#31]
Motivating case: Impinj readers make phase-angle information available in tag reports: https://support.impinj.com/hc/en-us/articles/202756348-Get-Low-Level-Reader-Data-with-LLRP

**Comment by electronicwhisper** [comment]
I'd like to use this information (specifically the Impinj data on phase angle) for the application I'm building.

If you gave me some pointers about what parts of the code I'd need to change in order to implement this I could take a shot at it. Thanks!

**Comment by ransford** [comment]
Hello!  To capture the phase-angle info from the Impinj reader, you'll have to change two things:
- The part that sets up the `ROSpec` (look for that string), which tells the reader what information to collect from its session, and
- The parser of `TagReportData`, of which you can see an example in `inventory.py`.

Somewhere in the Impinj spec you'll find the binary message format that the client must use to tell the reader it wants the extra fields.  I'm happy to help dig if you can get your hands on the right spec document.

**Comment by electronicwhisper** [comment]
Thank you for the response. Unfortunately I looked into this more and I think it will be too difficult for me as I don't have experience reverse engineering at this level.

Additionally, I found out that the Octane SDK from Impinj supports phase angle, doppler, etc., and all the examples compile cross-platform using Mono. Even not knowing C#, I was able to make minor modifications to one of the examples to get it to spit out the phase information to standard out so I'm now just running that as a subprocess from Python.

**Comment by ransford** [comment]
Aww, too bad, because I just figured out how to get this information out of readers via the Octane extensions.  If I manage to implement the changes in the next couple of weeks, are you willing to do a quick test of the `inventory` script against one of your nice Impinj readers? :-)

**Comment by electronicwhisper** [comment]
Sure, I can do a test. I have an R420.

**Comment by antmarko** [comment]
hello guys i m using speedway revolution reader on ubuntu.i would like to get phase-angle information on tag reports but i dont know how to config it.fow now i m using impinj's Sample Application but it only provide basic information like RSSI,TID etc.Could you please point me steps to follow?Thank you.

**Comment by ransford** [comment]
@antmarko what model of reader, and are you able to provide a `debug`-level log with `sllurp --debug --logfile impinj.log inventory <reader ip address>`?

**Comment by antmarko** [comment]
The model is Impinj Speedway Revolution R420.For now i haven't used sllurp library because i was trying to enable RF phase angle for tag reports using LTKCPP (in LTK's programmers guide says that it's possible to to do such thing using object-based construction pointing docsample4.cpp file,a file i dont know where to find,as well as using LTKCPP LTK_XML but i cann't succeed in both ways).

**Comment by ransford** [comment]
It looks like there may be a way to enable phase angle reporting via one of the Octane APIs; I visited https://support.impinj.com/hc/en-us/articles/202755288-Speedway-Revolution-Embedded-Development-Tools-and-Sample-Application and downloaded the big zip file, and found mentions of `PhaseAngle` in octane_etk_sample-5.10.1.240/include/out_impinj_ltkcpp.h.  I hope that gives you a clue as to how to configure phase-angle reporting.

**Comment by antmarko** [comment]
i know this file.it implements the necessary classes,messages etch (like phase-angle you mentioned).but the problem is i dont know how exactly to enable it.the source file that has to be altered is speedway_embedded_example.cpp.But if i choose to use sllurp what process should i follow?

**Comment by ransford** [comment]
Ah. I couldn't find enough information in the LLRP standard doc to answer your question, but maybe I can dig into the Octane-specific materials a little more, or of course you're welcome to do so.  If you manage to get *any* tool to send the right "enable phase angle reporting" command to your reader, please capture the LLRP traffic with tcpdump or Wireshark so we can pick it apart here.

**Comment by antmarko** [comment]
The only thing i could point, and i think it's the solution,is to mention this LTK's programmers guide  https://support.impinj.com/hc/article_attachments/115000055664/Impinj_LTK_Programmers_Guide.pdf in combination with speedway_embedded_example.cpp source file i mentioned earlier(that has to be modified).From pdf check chapter 10 Impinj Octane LTK Tag Data.

**Comment by ransford** [comment]
This seems to have lost momentum... feel free to open if there's something to be done about it.

**Comment by thijmenketel** [comment]
I'm trying to get the phase readings working but it is quite unclear for me how I need to edit llrp_proto.py and llrp.py to get this working. As far as I can understand the LTK programmers guide (chapter 10) the reader needs an extension to the rospec, but I don't really know how to implement that in sllurp.

**Comment by ransford** [comment]
I started implementing Impinj custom extensions this weekend in c9a92361d4ca1c22baaf10759c1a8ecd2432e8ba.  The first thing I added was dual target search mode for more frequent reads.  Enabling the phase angle extension probably involves similar modifications to the `C1G2InventoryCommand` in `llrp_proto.py` (look for the word `CustomParameter` and you'll see what I changed).

Is that helpful?

Since I haven't been able to find good documentation from Impinj on their custom extensions, I think you might have to use Wireshark to pick apart an LLRP ADD_ROSPEC message.  Use capture filter `port 5084` and you can watch LLRP messages between your host and the reader.

**Comment by thijmenketel** [comment]
Little bit of a noob here, I've got code from that commit running. However I'm not sure what to add to that to get the correct xml tags for the phase angle to be added to the rospec. Excuse if its obvious and I'm just missing it :).

**Comment by thijmenketel** [comment]
Btw, I did have trouble with finding the XML schema encoding. Furthermore, the inventorysearchextension you added is a different part of the octane extension. To enable the Phase reading (and others) the ImpinjTagReportContentSelector parameter needs to be added (according to the low level data support note). 

Do you think that can be implemented in a similar way as the regular TagReportContentSelector? (similar encoder function)

**Comment by ransford** [comment]
Can you link to the document you're referring to?  That would help me understand where we need to make changes in order to get phase angle in tag report content.  I have an Impinj reader to test against.

The types in the message structures are from the LLRP standard; if you're interested, you can look at the structure definitions in the LLRP spec in the `docs/` directory of this repo.

**Comment by thijmenketel** [comment]
The Low level reader support note is [Here](https://support.impinj.com/hc/en-us/articles/202755318-Application-Note-Low-Level-User-Data-Support)
LTK programming guide is [here](https://support.impinj.com/hc/article_attachments/360000030920/Impinj_LTK_Programmers_Guide.pdf) (chapter 10 has the extension parts in it)
And I got the XML schema from [here[(https://github.com/esitarski/CrossMgr/blob/master/CrossMgrImpinj/pyllrp/Impinjdef-1.18-private.xml) because I couldn't find it anywhere else. The ImpinjTagReportContentSelector part is on line 866.

I also have a reader to test (R1000) but I'll be out for a week from tomorrow so I can test again from next week tuesday. 

Ah yes, got me kind of confused but now its clear. It does beg the question which message types are needed to add the extensions. 

Thanks for the help BTW!

**Comment by thijmenketel** [comment]
According to the Octane guide (page 77 and 78) the ImpinjTagReportContentSelector (type 50 according to [this](https://github.com/esitarski/CrossMgr/blob/master/CrossMgrImpinj/pyllrp/Impinjdef-1.18-private.xml) xml schema) is extended to the ROReportSpec parameter (type 237 in the LLRP spec) and not to the C1G2InventoryCommand (I think, not sure). So I guess this can be implemented in a similar way to the TagReportContentSelector parameter. However, I'm struggling to understand the encoder functions of those parameters in sllurp which makes it hard to implement for me.

**Comment by thijmenketel** [comment]
So I figured out how to do it and I am now able to get the phase angle information. My current implementation is a little bit hacky though as only one of the impinj extensions (from the impinjtagreportcontentselector) can be added and the decoding is tailored only to the phase angle. I worked from the latest develop version and the search mode needs to be on (so either 1 or 2) to have the extensions enabled. 

Enabling the rest isn't that much more work I think but its a bit out of my scope (currently doing MsC thesis).

**Comment by li9i** [comment]
> The model is Impinj Speedway Revolution R420.For now i haven't used sllurp library because i was trying to enable RF phase angle for tag reports using LTKCPP (in LTK's programmers guide says that it's possible to to do such thing using object-based construction pointing docsample4.cpp file,a file i dont know where to find,as well as using LTKCPP LTK_XML but i cann't succeed in both ways).

I felt your pain @antmarko until I found the file in question. You can navigate yourself to [here](https://support.impinj.com/hc/en-us/articles/202755488-LTK-Libraries-for-Readers), click on `Download LTK C++ Linux (v10.34.0)`, and unpack the two compressed files.

I managed to get the phase angle in C++ by injecting the following piece of code in `speedway_embedded_example.cpp` after line 952:

```
...
pOptimizedRead->addC1G2Read(pUmOpSpec);

// BEGINNING
CImpinjEnableRFPhaseAngle       * pEnableRfPhase = new CImpinjEnableRFPhaseAngle();
pEnableRfPhase->setRFPhaseAngleMode(ImpinjRFPhaseAngleMode_Enabled);
pImpContentSelector->setImpinjEnableRFPhaseAngle(pEnableRfPhase);

CImpinjEnablePeakRSSI       * pEnablePeakRssi = new CImpinjEnablePeakRSSI();
pEnablePeakRssi->setPeakRSSIMode(ImpinjPeakRSSIMode_Enabled);
pImpContentSelector->setImpinjEnablePeakRSSI(pEnablePeakRssi);

CImpinjEnableSerializedTID  * pEnableSerializedTID = new CImpinjEnableSerializedTID();
pEnableSerializedTID->setSerializedTIDMode(ImpinjSerializedTIDMode_Disabled);
pImpContentSelector->setImpinjEnableSerializedTID(pEnableSerializedTID);

// Add the optimized read operations to the ROReportSpec
pImpContentSelector->setImpinjEnableOptimizedRead(pOptimizedRead);
pROrs->addCustom(pImpContentSelector);
// ENDING

// One AISpec
llrp_u16v_t AntennaIDs = llrp_u16v_t(1);
...
```
