### ISSUE TITLE
Upload to PyPi

### ISSUE THREAD

**Issue by JonasGroeger** [ransford/sllurp#6]
Hello!

It would be great to see the package up on PyPi. The procedure is as follows:

```
pip install --upgrade pip
pip install wheel
pip install twine
python setup.py sdist bdist_wheel

#dist/ should now contain 2 files (.whl, .tar.gz)
twine upload -u USERNAME -p PASSWORD dist/*
```

It would make sense for the author of this package, @ransford, to upload this to https://pypi.python.org/pypi

Thanks!

**Comment by ransford** [comment]
Done.  Decided not to close #7 although that work continues in the `feature/construct` branch.
