### ISSUE TITLE
Support for Python 3?

### ISSUE THREAD

**Issue by lqf96** [ransford/sllurp#66]
Both the sllurp CLI and the library fail to run under Python 3.6. Since official support for Python 2 is going to end at 2020, maybe we should update the code to make it work with Python 3.

**Comment by ransford** [comment]
Agreed.  We inherited some code from another library that was incompatible, so we inherited those incompatibilities.  If you're willing to help, you could attempt to run sllurp under Python 3 and identify the points where it breaks, then make a list here?
