### ISSUE TITLE
Writing a word in a user memory bank and reading the word 

### ISSUE THREAD

**Issue by redredder007** [ransford/sllurp#78]
I have no idea...

I am just a beginner. Can someone point me where to start? I will be very thankful :)

Nithin

**Comment by ransford** [comment]
Run `sllurp access --help` and you'll see some command-line options that may be helpful.  Good luck!

**Comment by redredder007** [comment]
That worked perfect. I have trouble reading the temperature from EM 4325. Did anyone try with sllrup? I will create new thread to benefit future users. Thanks

**Comment by ransford** [comment]
I haven't heard anything specifically related to the EM 4325, but am excited to see what you make!
