### ISSUE TITLE
Getting host + reader port info on callback

### ISSUE THREAD

**Issue by djacobson** [ransford/sllurp#81]
I have a sllurp client that is successfully reading scanner tag data via:

addTagReportCallback(some_call_func)

Inside the context of my callback, I would like to report which host (dst) and its port that called the call back (assuming multiple readers). I'm not sure how to add that type of arg data to the Protos? Insight would be appreciated.

**Comment by ransford** [comment]
Try this:

```python
def tagreport_callback(llrp_msg):
    def ip_address = llrp_msg.peername[0]
    print(ip_address)
    # ...
```

**Comment by djacobson** [comment]
This worked perfectly. Thank you!
