### ISSUE TITLE
Trouble getting sllurp to run 

### ISSUE THREAD

**Issue by sophiaabraham96** [ransford/sllurp#82]
I have been trying to install the library from github and after cloning and entering sllup, all the commands are not recognized and I am having trouble fixing that, any insight as to how I can properly get it running?

**Comment by ransford** [comment]
Here's the simplest sequence of steps:
```shell
$ python3 -m venv .venv
$ source .venv/bin/activate
(.venv) $ pip install sllurp
(.venv) $ sllurp inventory --help
```

I won't be able to help much beyond that, as I'm not sure what you've tried, what platform you're on, et cetera.

**Comment by sophiaabraham96** [comment]
Thank you for such a rapid response! And I may have installed it incorrectly or missing something but really new to all of this so maybe I can provide greater clarity. I downloaded git and python and added to the path but then none of the commands are being found. Did I miss a step in the middle? I can enter the sllurp directory and then when I try to enter virtualenv .venv the response is "command not found". I am using a windows machine and running from a git bash terminal.

**Comment by ransford** [comment]
sllurp isn't special with respect to installation, so I would suggest finding a good tutorial that specifically applies to your configuration.  If you can `pip install requests`, for example, then you can `pip install sllurp`!

**Comment by sophiaabraham96** [comment]
Hmm so an error of "bash: .venv/bin/activate: No such file or directory" would be a configuration issue I would need to fix?

**Comment by sophiaabraham96** [comment]
Wait I think I need Microsoft Visual installed and I did not have that! I will try it again, I really appreciate all your help!! :)

**Comment by sophiaabraham96** [comment]
![image](https://user-images.githubusercontent.com/32935369/41990845-9b7e1998-7a11-11e8-87d8-e88e3c8ac1cf.png)

I was wondering if you did have a tutorial available on utilizing sllurp with the wisp5 in addition to the readme? Lol I seem to be very bad at this :)

**Comment by thijmenketel** [comment]
Make sure that you are running it through python3 as some of the methods are only available in that.

**Comment by sophiaabraham96** [comment]
I thought there were incompatibilities with python3? I guess I will attempt that and see if the issues are resolved, thank you :)

**Comment by sophiaabraham96** [comment]
I was able to get it properly installed :) I just needed to download some window binaries and place them in the correct folders to properly get it working, thank you both for the suggestions and help! :)

**Comment by ransford** [comment]
Yes, it's mostly a library for building your own applications.  Have fun!
